# -*- coding: utf-8 -*-
"""4G03-HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153-znd8fNmJFUHbENTZVsT5FInNfut5R
"""

from matplotlib import pyplot as plt
import numpy as np

# array from text file
data = np.loadtxt("./drive/MyDrive/Data/histogram.txt")
data2 = np.loadtxt("./drive/MyDrive/Data/histogram2.txt")
  
print(data)

x = list(range(len(data)))

print(x)

# Creating histogram
fig, ax = plt.subplots(figsize =(10, 7))

ax.bar(x, data)
ax.set_xlabel("MonteCarlo time (measurements)", fontsize = '14')
ax.set_ylabel("M (magnetization)", fontsize = '14')
ax.set_title("T = 2.26", fontsize = '16')
 
# Show plot
plt.show()
plt.savefig("T_2_26.png",dpi=800)

# Creating histogram
fig, ax = plt.subplots(figsize =(10, 7))

ax.bar(x, data2)
ax.set_xlabel("MonteCarlo time (measurements)", fontsize = '14')
ax.set_ylabel("M (magnetization)", fontsize = '14')
ax.set_title("T = 2.45", fontsize = '16')
 
# Show plot
plt.show()
plt.savefig("T_2_45.png",dpi=800)

data_E_avg = './drive/MyDrive/Data/E_avg.txt'

E_avg = np.loadtxt(
    data_E_avg,
    unpack=True
)

data_chi = './drive/MyDrive/Data/chi.txt'

chi = np.loadtxt(
    data_chi,
    unpack=True
)

data_C_v = './drive/MyDrive/Data/C_v.txt'

C_v = np.loadtxt(
    data_C_v,
    unpack=True
)

data_g8 = './drive/MyDrive/Data/g_8.txt'

g8 = np.loadtxt(
    data_g8,
    unpack=True
)

data_g12 = './drive/MyDrive/Data/g_12.txt'

g12 = np.loadtxt(
    data_g12,
    unpack=True
)

data_g16 = './drive/MyDrive/Data/g_16.txt'

g16 = np.loadtxt(
    data_g16,
    unpack=True
)

E_avg.size

T = []
for t in range(E_avg.size):
  i = 2.0 + (0.5*(t/(E_avg.size)))
  T.append(i)

print (T)

print (len(T))

fig, ax = plt.subplots(figsize =(10, 7))

ax.plot(T, E_avg)
ax.set_xlabel("temperature (T)", fontsize = '14')
ax.set_ylabel("<E>", fontsize = '14')
ax.set_title("E_avg vs T", fontsize = '16')
 
# Show plot
plt.show()
plt.savefig("E_avg.png",dpi=800)

fig, ax = plt.subplots(figsize =(10, 7))

ax.plot(T, chi)
ax.set_xlabel("temperature (T)", fontsize = '14')
ax.set_ylabel("Chi", fontsize = '14')
ax.set_title("chi vs T", fontsize = '16')
 
# Show plot
plt.show()
plt.savefig("chi.png",dpi=800)

fig, ax = plt.subplots(figsize =(10, 7))

ax.plot(T, C_v)
ax.set_xlabel("temperature (T)", fontsize = '14')
ax.set_ylabel("<C_v>", fontsize = '14')
ax.set_title("C_v vs T", fontsize = '16')
 
# Show plot
plt.show()
plt.savefig("C_v.png",dpi=800)

fig, ax = plt.subplots(figsize =(10, 7))

ax.plot(T, g8, label="L = 8")
ax.plot(T, g12, label="L = 12")
ax.plot(T, g16, label="L = 16")
ax.set_xlabel("temperature (T)", fontsize = '14')
ax.set_ylabel("g(L, T)", fontsize = '14')
ax.set_title("g(L, T) vs T", fontsize = '16')
 
# Show plot
plt.legend()
plt.show()
plt.savefig("g.png",dpi=800)

